# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_genre_movie_moviegenre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='accesstoken',
            old_name='users_id',
            new_name='user',
        ),
    ]
